# Generated by Django 5.1.4 on 2025-02-02 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0005_alter_category_options_alter_photo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='name',
            new_name='user',
        ),
    ]
