# Generated by Django 5.1.4 on 2025-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appofc', '0008_alter_member_image_alter_member_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
    ]
